### ISSUE TITLE
Hosted documentation

### ISSUE THREAD

**Issue by vladfaust** [will/crystal-pg#109]
References to #108
BTW, glad this repo is alive! :smile: 

Travis CI offers [Github Pages deployments](https://docs.travis-ci.com/user/deployment/pages/), and it's very neat. I personally use it for my projects. Check the example `.travis.yml`:
```yaml
language: crystal
script: crystal docs
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master
  local_dir: doc
```

I will be happy if you setup hosted documentation!
