### ISSUE TITLE
Syntax error from using group

### ISSUE THREAD

**Issue by jwoertink** [will/crystal-pg#91]
I have a table that has a column called "group". Trying to query with this fails:

```
icr(0.21.1) > PG.query_all("SELECT group FROM hosted_ads", as: {String})
syntax error at or near "FROM" (PQ::PQError)
0x1072e6ce5: *CallStack::unwind:Array(Pointer(Void)) at ??
0x1072e6c81: *CallStack#initialize:Array(Pointer(Void)) at ??
0x1072e6c58: *CallStack::new:CallStack at ??
0x1072b3441: *raise<Exception+>:NoReturn at ??
0x10746b17a: *DB::Statement+@DB::Statement#perform_query_with_rescue<Tuple()>:PG::ResultSet at ??
0x10746b11a: *DB::Statement+@DB::Statement#query:PG::ResultSet at ??
0x10748369d: *DB::PoolStatement+@DB::PoolStatement#query:PG::ResultSet at ??
0x10744ffb5: *DB::Database@DB::QueryMethods#query<String>:PG::ResultSet at ??
0x10744feb9: *DB::Database@DB::QueryMethods#query_all:as<String, Tuple(String:Class)>:Array(String) at ??
0x1072e5361: *__icr_exec__:Array(String) at ??
0x1072954a7: __crystal_main at ??
0x1072a7198: main at ??
```

I'm using Crystal 0.21.1 with:

```
db:
  github: crystal-lang/crystal-db
  version: 0.4.1
pg:
  github: will/crystal-pg
  commit: cafe681e9fbc520b5152632e22571bbef88a68d1
```
